#!/usr/bin/env python3

# Script that generates 34 groups (nGroups) each consisting of 24 robot 3-tuples.
# The groups are generated by populating them with random elements from all the
# possible combinations of 18 robots in 3-tuples.

import robotTuples as rT
import matplotlib.pyplot as plt
from collections import Counter, OrderedDict
from random import seed
from datetime import datetime

n = 18 # total number of robots
k = 3  # number of robots per tuple
groupSize = 24 # number of tuples per group
nGroups = 34 # number of groups desired
margin = 24 # parameter that defines the number of "new" tuples needed to accept group

# creates list of robots:
robots = list(range(1,n+1))

# generates all the possible tuples with the above given parameters:
totalTuples = rT.possibleTuples(robots,k)
totalCombis = len(totalTuples) # number of available tuples to choose from

print(f"\nWith {n} robots, there are {totalCombis} posible combinations of {k}-tuples.\n\nWe will construct {nGroups} groups of {k}-tuples, each consisting of {groupSize} elements.\n\nEvery robot should appear {4} times in each group.")

# initializes dictionary where groups will be stored:
groupsDictionary = {}
# generates groups using the functions available in the file 'robotTuples.py':
iter=0
countr=0
trial=0
while iter<nGroups:
    # creates all possible tuples defined by the parameters from above:
    totalTuples=rT.possibleTuples(robots,k)
    # generates a group which fulfills the constraints:
    currentGroup=rT.generateGroupInSilence(totalTuples, groupSize)
    # add the created group to a dictionary:
    groupsDictionary.update({iter:currentGroup})
    trial=trial+1
    # extracts every robot tuple from dictionary then makes a list:
    total = groupsDictionary.values()
    tupleList = [tuple for group in total for tuple in group]
    # print(f"\nThe total list of tuples is: {tupleList}. It has {len(tupleList)} elements.")
    oldCountr=countr
    # Counts the number of times each tuple appears in the total list:
    count = Counter(tupleList)
    countr = len(count)
    if iter<18:
        margin=24
    else:
        margin=20

    if trial%100==0:
        print(f"\nTrial {trial}: Group {iter+1}/{34} would add {countr-oldCountr} new tuples (we want {margin}). Total unique tuples: {countr}.\n")

    if countr >= oldCountr+margin:
        print(f"\nWe have created {iter+1} groups. We used {countr} tuples from the {totalCombis} possible ones.\n")
        iter=iter+1
        # print(groupsDictionary)
    else:
        groupsDictionary.pop(iter)
        countr = oldCountr




totalTuples = rT.possibleTuples(robots,k)
myList=list(OrderedDict.fromkeys(tupleList))
orderedCount = OrderedDict(count.most_common())
diffList=list(set(totalTuples) - set(tupleList))
# print(diffList)
# print(f"\nThe number of tuples used in the solution set is: {len(myList)} out of the {len(totalTuples)} possible ones. They are:\n")
# print(f"tuple\t\ttimes seen\n-----\t\t----------")
# for key, value in orderedCount.items():
#         print(f"{key}\t:{value}")
# print(f"\nThe number of tuples not used in the group is: {len(diffList)}. They are:\n")
# print(f"tuple\t\ttimes seen\n-----\t\t----------")
# for tuple in sorted(diffList):
#         print(f"{tuple}\t:{0}")
# diffCount = Counter(diffList)


## Saving output of experiment
# gets the current date and time to generate a unique filename for storing results:
now = datetime.now()
date1 = now.strftime("%Y:%m:%d")
date2 = now.strftime("%Y/%m/%d")
time = now.strftime("%H:%M:%S")

# prints resulting groups to unique file with human readable format:
with open(f"TupleResults.txt", 'w+') as file:
    file.write(f"\nThe total number of tuples is: {len(totalTuples)}.\n")
    file.write(f"\nThe number of tuples used in the solution set is: {len(myList)}. They are:\n")
    file.write(f"\ntuple\t\ttimes used\n-----\t\t----------\n")
    for key, value in orderedCount.items():
            file.write(f"{key}\t:{value}\n")
    file.write(f"\nThe number of tuples not used in the solution set is: {len(diffList)}. They are:\n")
    file.write(f"\ntuple\t\ttimes used\n-----\t\t----------\n")
    for tuple in sorted(diffList):
            file.write(f"{tuple} \t:{0}\n")

# prints resulting groups to unique file with human readable format:
with open(f"Results.txt", 'w+') as file:
    file.write(f"The following solution set of groups was created on {date2} at {time}.\n\nThere solution set uses a total of {countr} unique tuples from the {totalCombis} possible ones.\n")
    # file.write(f"We have:\n {count}\n")
    for i in range(0,nGroups):
        file.write(f"\n Group {i+1}: {groupsDictionary[i]}\n")

    file.write(f"\nThere are a total of {len(diffList)} unused tuples from the {totalCombis} possible ones.\n")
    file.write(f"\n Unused Group: {diffList}\n")

# prints resulting groups to another unique file for javascript experiment:
with open(f"Results_js.txt", 'w+') as file:
    for i in range(0,nGroups):
        file.write(f"\n---------Group{i+1}---------\n")
        for tuple in groupsDictionary[i]:
            idx = groupsDictionary[i].index(tuple)
            file.write(f"var set{idx+1} = {list(tuple)};\n")

# prints resulting groups to another unique file for javascript experiment:
# with is like your try .. finally block in this case

for i in range(nGroups):
    with open('experiment.html', 'r') as file:
        # read a list of lines into data
        data = file.readlines()

    with open(f"experiment_{i+1}.html", 'w+') as file:
        for tuple in groupsDictionary[i]:
            idx = groupsDictionary[i].index(tuple)
            data[12+idx] = f"    var set{idx+1} = {list(tuple)};\n"

        file.writelines(data)






# Huh?
print(f"\nDid this work?.\n")

# 24        1
# 48        2
# 72        3
# 96        4
# 120       5
# 144       6
# 168       7
# 192       8
# 216       9
# 240       10
# 264       11
# 288       12
# 312       13
# 336       14
# 360       15
# 384       16
# 408       17
# 432       18
# 456       19
# 480       20
# 504       21
# 528       22
# 552       23
# 576       24
# 600       25
# 624       26
# 648       27
# 672       28
# 696       29
# 720       30
# 744       31
# 768       32
# 792       33
# 814       34

# 24*15+(19*17)=683
